# Generated by Django 4.2.2 on 2024-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('abilities', models.ManyToManyField(to='ability.wish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
