# Generated by Django 4.2.2 on 2024-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
