# Generated by Django 4.2.2 on 2024-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='abilities',
            field=models.ManyToManyField(to='ability.ability'),
        ),
    ]
