version: '3'
services:
  web:
    build: .
    command:
      bash -c "
      sleep 1
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - .:/app
      - ./static:/var/static
      - ./uploads:/var/uploads
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - redis
    links:
      - redis:redis
    env_file:
      - .env

  celery:
    build: .
    depends_on:
      - redis
    env_file:
       - .env
    volumes:
      - .:/app
    command: >
      bash -c "
              sleep 3 &&
              celery -A backend worker -E -B -ldebug
              "

  redis:
    image: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"

volumes:
  postgres_data: