# Generated by Django 4.2.2 on 2024-08-29 08:14

import ability.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('media', models.FileField(blank=True, null=True, upload_to='ability_media/', validators=[ability.models.validate_media])),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('subscribers', 'Subscribers'), ('everyone', 'Everyone'), ('only_me', 'Only_me')], default='everyone', max_length=20)),
                ('currency', models.CharField(blank=True, choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('NOK', 'NOK'), ('CHF', 'CHF'), ('SEK', 'SEK')], max_length=50, null=True)),
                ('is_fully_created', models.BooleanField(default=False)),
            ],
        ),
    ]
