# Generated by Django 4.2.2 on 2024-08-22 10:47

import ability.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('media', models.FileField(blank=True, null=True, upload_to='ability_media/', validators=[ability.models.validate_media])),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('subscribers', 'Subscribers'), ('everyone', 'Everyone'), ('only_me', 'Only_me'), ('chosen_ones', 'ChosenOnes')], default='subscribers', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
